import { z } from "zod";

const trainingHistorySchema = z.object({
    id: z.string(),
    school: z.string(),
    major: z.string(),
    startDate: z.string(),
    endDate: z.string(),
    type: z.string(),
    degree: z.string(),
});

export type TrainingHistory = z.infer<typeof trainingHistorySchema>;

export const profileFormSchema = z.object({
    employeeId: z.string().min(1, "Mã nhân viên là bắt buộc"),
    fullName: z.string().min(1, "Họ và tên là bắt buộc"),
    gender: z.enum(["male", "female", "other"]),
    dob: z.string().optional(),
    birthPlace: z.string().optional(),
    hometown: z.string().optional(),
    ethnicity: z.string().optional(),
    religion: z.string().optional(),
    idNumber: z.string().min(1, "Số CMND/CCCD là bắt buộc"),
    idIssueDate: z.string().optional(),
    phone: z.string().min(1, "Số điện thoại là bắt buộc"),
    email: z.string().email("Email không hợp lệ").min(1, "Email là bắt buộc"),
    permanentAddress: z.string().optional(),
    currentAddress: z.string().optional(),
    avatar: z.string().optional().nullable(),

    // Professional Information
    position: z.string().optional(),
    department: z.string().optional(),
    jobTitle: z.string().optional(),
    hireDate: z.string().optional(),
    hireAgency: z.string().optional(),
    rank: z.string().optional(),
    salary: z.string().optional(),
    salaryDate: z.string().optional(),
    education: z.string().optional(),
    specialization: z.string().optional(),
    politics: z.string().optional(),
    management: z.string().optional(),
    languageLevel: z.string().optional(),
    it: z.string().optional(),
    partyJoinDate: z.string().optional(),
    partyOfficialDate: z.string().optional(),
    health: z.string().optional(),
    familyPolicy: z.string().optional(),

    // Additional Information
    socialOrgJoinDate: z.string().optional(),
    enlistmentDate: z.string().optional(),
    dischargeDate: z.string().optional(),
    highestMilitaryRank: z.string().optional(),
    highestTitle: z.string().optional(),
    forte: z.string().optional(),
    reward: z.string().optional(),
    discipline: z.string().optional(),
    bhxhNumber: z.string().optional(),

    // Training history
    trainings: z.array(trainingHistorySchema),
});

export type ProfileFormData = z.infer<typeof profileFormSchema>;

export const getDefaultProfileValues = (): ProfileFormData => ({
    employeeId: "",
    fullName: "",
    gender: "male",
    dob: "",
    birthPlace: "",
    hometown: "",
    ethnicity: "",
    religion: "",
    idNumber: "",
    idIssueDate: "",
    phone: "",
    email: "",
    permanentAddress: "",
    currentAddress: "",
    avatar: null,
    position: "",
    department: "",
    jobTitle: "",
    hireDate: "",
    hireAgency: "",
    rank: "",
    salary: "",
    salaryDate: "",
    education: "",
    specialization: "",
    politics: "",
    management: "",
    languageLevel: "",
    it: "",
    partyJoinDate: "",
    partyOfficialDate: "",
    health: "",
    familyPolicy: "",
    socialOrgJoinDate: "",
    enlistmentDate: "",
    dischargeDate: "",
    highestMilitaryRank: "",
    highestTitle: "",
    forte: "",
    reward: "",
    discipline: "",
    bhxhNumber: "",
    trainings: [],
});